steps:
  - label: "Triggering pipelines"
    command: env
  - wait
  - label: "Install dependencies"
    command: 
    - npm i
    - tar -czvf node_modules.tar.gz ./node_modules
    artifact_paths: node_modules.tar.gz
  - wait
  - label: Build
    command:
    - buildkite-agent artifact download node_modules.tar.gz .
    - tar -xzvf node_modules.tar.gz
    - npm run build
    - tar -czvf dist.tar.gz ./dist
    artifact_paths: dist.tar.gz
  - wait